service: fargate-api

provider:
  name: aws
  region: us-east-1

plugins:
  - serverless-fargate

custom:
  fargate:
    clusterName: fargate-cluster
    securityGroupIds:
      - sg-03609c89aa1549572
    subnetIds:
      - subnet-0773bb21b51055b94
      - subnet-09b6d2a541f807471

fargate:
  app:
    image: 780673962482.dkr.ecr.us-east-1.amazonaws.com/fargate-api:latest
    cpu: "256"
    memory: "512"
    port: 3000
    alb:
      listenerArn: arn:aws:elasticloadbalancing:us-east-1:780673962482:listener/app/my-load-balancer/f79d6814d1a14b9a/f9fd786bfa70f045
      healthCheckPath: /ping

resources:
  Resources:
    ExecutionRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - ecs-tasks.amazonaws.com
              Action:
                - sts:AssumeRole
        Policies:
          - PolicyName: ECSExecutionPolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - ecr:GetAuthorizationToken
                    - ecr:BatchCheckLayerAvailability
                    - ecr:GetDownloadUrlForLayer
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: "*"

    TaskRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - ecs-tasks.amazonaws.com
              Action:
                - sts:AssumeRole
